name: eBPF Sketches Test
on:
  workflow_run:
    workflows: ["eBPF Sketches Build & Publish"]
    types:
      - completed

jobs:
  count-sketch:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: System info
      run: |
        uname -a
        ip addr
    - name: Pull docker container
      run: |
        docker pull sebymiano/ebpf-sketches:latest
    - name: Test count-sketch
      uses: addnab/docker-run-action@v3
      with:
          image: sebymiano/ebpf-sketches:latest
          options: --privileged --network=host --pid=host
          run: |
              sudo timeout --preserve-status -s SIGINT 30 \
              sudo python3 count_sketch.py -i lo -m NATIVE -a DROP