name: eBPF Sketches Test
on:
  workflow_run:
    workflows: ["eBPF Sketches Build & Publish"]
    types:
      - completed

jobs:
  count-sketch:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    container:
      image: sebymiano/ebpf-sketches:latest
      options: --privileged --pid=host
      volumes:
        - /sys/kernel/debug:/sys/kernel/debug:rw
        - /lib/modules:/lib/modules:ro
        - /usr/src:/usr/src:ro
        - /usr/include/linux:/usr/include/linux:ro
    steps:
      - name: System info
        run: |
          uname -a
      - name: Test count-sketch
        run: |
          sudo timeout --preserve-status -s SIGINT 30 \
          sudo python3 count_sketch.py -i lo -m NATIVE -a DROP