name: eBPF Sketches Test

on: push

env:
  BUILD_TYPE: Debug

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: System info
      run: |
        uname -a
    - name: Configure and Build
      run: |
        chmod +x "${GITHUB_WORKSPACE}/install-requirements.sh"
        ${GITHUB_WORKSPACE}/install-requirements.sh
    - name: Test count-sketch
      run: |
        sudo timeout --preserve-status -s SIGINT 30 sudo python3 ${GITHUB_WORKSPACE}/count_sketch.py -i lo -m NATIVE -a DROP